/*

	1 Give the next five pseudorandom numbers generated by the process described on
	page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.

*/

import java.util.Random;

class Random_Number{

	public static void main(String[] args) {
		int ans[] =new int[5];
		Random r = new Random();
		int a = 12 , b = 5 , n =100;
		for(int i = 0 ; i < 5 ;  i++){

			int cur = r.nextInt();

			//int next = (a ∗ cur + b) % n;
			int next = (a * cur + b ) % n;
			ans[i] = next;

		}

		for (int i = 0 ; i < ans.length ; i++) {
			
			System.out.println(ans[i]);
		}
	}
}